version: "3.8"

services:
  api:
    build: .
    container_name: lfsd_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: lfsd_redis
    ports:
      - "6379:6379"