apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: hamoum/lfsd:latest
        ports:
        - containerPort: 5000
        livenessProbe:
         httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 3
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3

        readinessProbe:
         httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 3
        timeoutSeconds: 1
        periodSeconds: 5
        failureThreshold: 3
