apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-user: dXNlcm5hbWU=        # base64 encoded username
  db-password: cGFzc3dvcmQ=    # base64 encoded password
  db-name: ZGJfbmFtZQ==        # base64 encoded database name
