"""Initial_Cloud_Migration

Revision ID: 40e4ecf6df0c
Revises: 
Create Date: 2025-12-20 12:51:46.948608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e4ecf6df0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('system_info', sa.JSON(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_endpoint'), 'bug_reports', ['endpoint'], unique=False)
    op.create_index(op.f('ix_bug_reports_error_type'), 'bug_reports', ['error_type'], unique=False)
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.create_index(op.f('ix_bug_reports_request_id'), 'bug_reports', ['request_id'], unique=False)
    op.create_index(op.f('ix_bug_reports_status'), 'bug_reports', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('viv_preferences', sa.JSON(), nullable=True),
    sa.Column('onboarding_status', sa.String(), nullable=True),
    sa.Column('onboarding_step', sa.String(), nullable=True),
    sa.Column('onboarding_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_meeting', sa.Boolean(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('location_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_table('feature_interests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_interests_user_id'), 'feature_interests', ['user_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_user_id'), 'financial_accounts', ['user_id'], unique=False)
    op.create_table('financial_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('income_stability_score', sa.Float(), nullable=True),
    sa.Column('burn_rate_score', sa.Float(), nullable=True),
    sa.Column('savings_momentum_score', sa.Float(), nullable=True),
    sa.Column('debt_stress_score', sa.Float(), nullable=True),
    sa.Column('recurring_commitments_score', sa.Float(), nullable=True),
    sa.Column('spending_stability_score', sa.Float(), nullable=True),
    sa.Column('liquidity_cushion_score', sa.Float(), nullable=True),
    sa.Column('risk_indicator_score', sa.Float(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('data_sources_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_scores_timestamp'), 'financial_scores', ['timestamp'], unique=False)
    op.create_index(op.f('ix_financial_scores_user_id'), 'financial_scores', ['user_id'], unique=False)
    op.create_table('health_daily_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('hrv_average', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_daily_summaries_date'), 'health_daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_health_daily_summaries_user_id'), 'health_daily_summaries', ['user_id'], unique=False)
    op.create_table('health_data_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('avg_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_data_samples_date'), 'health_data_samples', ['date'], unique=False)
    op.create_index(op.f('ix_health_data_samples_user_id'), 'health_data_samples', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('diet_style', sa.String(), nullable=True),
    sa.Column('water_intake_range', sa.String(), nullable=True),
    sa.Column('smoking_pattern', sa.String(), nullable=True),
    sa.Column('alcohol_pattern', sa.String(), nullable=True),
    sa.Column('stress_level', sa.String(), nullable=True),
    sa.Column('energy_pattern', sa.String(), nullable=True),
    sa.Column('activity_self_report', sa.String(), nullable=True),
    sa.Column('lifestyle_habits_json', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=False)
    op.create_table('life_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('saved_amount', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('impact_vector_json', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_goals_user_id'), 'life_goals', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('mobility_trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('dropoff_time', sa.DateTime(), nullable=True),
    sa.Column('cost_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobility_trips_user_id'), 'mobility_trips', ['user_id'], unique=False)
    op.create_table('sleep_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('wake_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_sessions_user_id'), 'sleep_sessions', ['user_id'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('total_debits', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('time_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_events_start_time'), 'time_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_time_events_user_id'), 'time_events', ['user_id'], unique=False)
    op.create_table('time_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('work_status', sa.String(), nullable=True),
    sa.Column('work_hours_per_week', sa.String(), nullable=True),
    sa.Column('uses_digital_calendar', sa.String(), nullable=True),
    sa.Column('commute_duration', sa.String(), nullable=True),
    sa.Column('time_meals_house_daily', sa.String(), nullable=True),
    sa.Column('time_admin_weekly', sa.String(), nullable=True),
    sa.Column('main_time_drains', sa.JSON(), nullable=True),
    sa.Column('routine_style', sa.String(), nullable=True),
    sa.Column('task_style', sa.String(), nullable=True),
    sa.Column('time_overwhelm_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_profiles_user_id'), 'time_profiles', ['user_id'], unique=False)
    op.create_table('time_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('load_score', sa.Float(), nullable=True),
    sa.Column('focus_score', sa.Float(), nullable=True),
    sa.Column('friction_score', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_scores_timestamp'), 'time_scores', ['timestamp'], unique=False)
    op.create_index(op.f('ix_time_scores_user_id'), 'time_scores', ['user_id'], unique=False)
    op.create_table('viv_indexes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('time_score', sa.Float(), nullable=True),
    sa.Column('snapshot_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viv_indexes_timestamp'), 'viv_indexes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_viv_indexes_user_id'), 'viv_indexes', ['user_id'], unique=False)
    op.create_table('viv_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_intent', sa.String(), nullable=True),
    sa.Column('context_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('decision_logic', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viv_logs_timestamp'), 'viv_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_viv_logs_user_id'), 'viv_logs', ['user_id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True),
    sa.Column('perceived_exertion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('statement_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('merchant_category_code', sa.String(), nullable=True),
    sa.Column('category_primary', sa.String(), nullable=True),
    sa.Column('category_detailed', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_viv_logs_user_id'), table_name='viv_logs')
    op.drop_index(op.f('ix_viv_logs_timestamp'), table_name='viv_logs')
    op.drop_table('viv_logs')
    op.drop_index(op.f('ix_viv_indexes_user_id'), table_name='viv_indexes')
    op.drop_index(op.f('ix_viv_indexes_timestamp'), table_name='viv_indexes')
    op.drop_table('viv_indexes')
    op.drop_index(op.f('ix_time_scores_user_id'), table_name='time_scores')
    op.drop_index(op.f('ix_time_scores_timestamp'), table_name='time_scores')
    op.drop_table('time_scores')
    op.drop_index(op.f('ix_time_profiles_user_id'), table_name='time_profiles')
    op.drop_table('time_profiles')
    op.drop_index(op.f('ix_time_events_user_id'), table_name='time_events')
    op.drop_index(op.f('ix_time_events_start_time'), table_name='time_events')
    op.drop_table('time_events')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_sleep_sessions_user_id'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    op.drop_index(op.f('ix_mobility_trips_user_id'), table_name='mobility_trips')
    op.drop_table('mobility_trips')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_life_goals_user_id'), table_name='life_goals')
    op.drop_table('life_goals')
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_health_data_samples_user_id'), table_name='health_data_samples')
    op.drop_index(op.f('ix_health_data_samples_date'), table_name='health_data_samples')
    op.drop_table('health_data_samples')
    op.drop_index(op.f('ix_health_daily_summaries_user_id'), table_name='health_daily_summaries')
    op.drop_index(op.f('ix_health_daily_summaries_date'), table_name='health_daily_summaries')
    op.drop_table('health_daily_summaries')
    op.drop_index(op.f('ix_financial_scores_user_id'), table_name='financial_scores')
    op.drop_index(op.f('ix_financial_scores_timestamp'), table_name='financial_scores')
    op.drop_table('financial_scores')
    op.drop_index(op.f('ix_financial_accounts_user_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_feature_interests_user_id'), table_name='feature_interests')
    op.drop_table('feature_interests')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('orders')
    op.drop_table('onboarding_sessions')
    op.drop_table('notifications')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_bug_reports_status'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_request_id'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_error_type'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_endpoint'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
