"""initial_schema_unified

Revision ID: fa3544f15155
Revises: 
Create Date: 2026-01-25 07:26:37.468519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa3544f15155"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("changes_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_correlation_id"),
        "audit_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "onboarding_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("data_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tier_configs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tier_configs_plan_id"), "tier_configs", ["plan_id"], unique=True
    )
    op.create_table(
        "users_v2",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("auth0_id", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("profile_json", sa.JSON(), nullable=True),
        sa.Column("viv_preferences", sa.JSON(), nullable=True),
        sa.Column("account_status", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("onboarding_status", sa.String(), nullable=True),
        sa.Column("onboarding_step", sa.String(), nullable=True),
        sa.Column("onboarding_version", sa.Integer(), nullable=True),
        sa.Column("password_reset_token", sa.String(), nullable=True),
        sa.Column("password_reset_expires", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_v2_auth0_id"), "users_v2", ["auth0_id"], unique=True)
    op.create_index(op.f("ix_users_v2_email"), "users_v2", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_v2_password_reset_token"),
        "users_v2",
        ["password_reset_token"],
        unique=False,
    )
    op.create_table(
        "activity_feed",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=False),
        sa.Column("action_link", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_feed_correlation_id"),
        "activity_feed",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_feed_created_at"),
        "activity_feed",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_feed_event_type"),
        "activity_feed",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_feed_user_id"), "activity_feed", ["user_id"], unique=False
    )
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_bgjob_progress_0_100"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_jobs_created_at"),
        "background_jobs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_dedupe_key"),
        "background_jobs",
        ["dedupe_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_job_type"),
        "background_jobs",
        ["job_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_updated_at"),
        "background_jobs",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_user_id"), "background_jobs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_bgjob_expires_at", "background_jobs", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_bgjob_status_updated",
        "background_jobs",
        ["status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "bug_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "severity", sa.Enum("ERROR", "CRITICAL", name="bugseverity"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", "IGNORED", name="bugstatus"),
            nullable=False,
        ),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("source_file", sa.String(length=255), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("system_info", sa.JSON(), nullable=False),
        sa.Column("request_headers", sa.JSON(), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bug_reports_endpoint"), "bug_reports", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_bug_reports_error_type"), "bug_reports", ["error_type"], unique=False
    )
    op.create_index(op.f("ix_bug_reports_id"), "bug_reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_bug_reports_request_id"), "bug_reports", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_bug_reports_status"), "bug_reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_bug_reports_user_id"), "bug_reports", ["user_id"], unique=False
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_meeting", sa.Boolean(), nullable=True),
        sa.Column("attendee_count", sa.Integer(), nullable=True),
        sa.Column("location_context", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_calendar_events_user_start",
        "calendar_events",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_start_time"),
        "calendar_events",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_user_id"), "calendar_events", ["user_id"], unique=False
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("credentials_json", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("token_type", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="ux_user_provider"),
    )
    op.create_index(
        op.f("ix_connections_user_id"), "connections", ["user_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "feature_interests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("feature_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feature_interests_user_id"),
        "feature_interests",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "financial_accounts_v2",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("institution_name", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("current_balance", sa.Float(), nullable=True),
        sa.Column("limit", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_accounts_v2_user_id"),
        "financial_accounts_v2",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "financial_scores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("cashflow_stability_score", sa.Float(), nullable=True),
        sa.Column("bills_coverage_score", sa.Float(), nullable=True),
        sa.Column("discretionary_control_score", sa.Float(), nullable=True),
        sa.Column("savings_rate_score", sa.Float(), nullable=True),
        sa.Column("emergency_buffer_score", sa.Float(), nullable=True),
        sa.Column("debt_load_score", sa.Float(), nullable=True),
        sa.Column("networth_momentum_score", sa.Float(), nullable=True),
        sa.Column("investment_health_score", sa.Float(), nullable=True),
        sa.Column("time_window", sa.String(), nullable=True),
        sa.Column("data_sources_json", sa.JSON(), nullable=True),
        sa.Column("total_monthly_income", sa.Float(), nullable=True),
        sa.Column("total_monthly_expenses", sa.Float(), nullable=True),
        sa.Column("total_monthly_bills", sa.Float(), nullable=True),
        sa.Column("total_monthly_savings", sa.Float(), nullable=True),
        sa.Column("total_assets_value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_scores_timestamp"),
        "financial_scores",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_scores_user_id"),
        "financial_scores",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "health_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_HEALTH",
                "WHOOP",
                "FITBIT",
                "GARMIN",
                "OURA",
                "GOOGLE_FIT",
                name="healthprovider",
            ),
            nullable=False,
        ),
        sa.Column("credentials", sa.String(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "REVOKED", "ERROR", name="connectionstatus"),
            nullable=False,
        ),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_health_conn_user_provider"),
    )
    op.create_index(
        "ix_health_conn_user_status",
        "health_connections",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_connections_provider"),
        "health_connections",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_connections_user_id"),
        "health_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "health_daily_summaries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_quality_score", sa.Float(), nullable=True),
        sa.Column("hrv_average", sa.Float(), nullable=True),
        sa.Column("resting_heart_rate", sa.Integer(), nullable=True),
        sa.Column("steps_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_health_summary_user_date",
        "health_daily_summaries",
        ["user_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_daily_summaries_date"),
        "health_daily_summaries",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_daily_summaries_user_id"),
        "health_daily_summaries",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "health_data_samples",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("active_minutes", sa.Integer(), nullable=True),
        sa.Column("calories_kcal", sa.Float(), nullable=True),
        sa.Column("resting_hr_bpm", sa.Integer(), nullable=True),
        sa.Column("avg_hr_bpm", sa.Integer(), nullable=True),
        sa.Column("sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_data_samples_date"),
        "health_data_samples",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_data_samples_user_id"),
        "health_data_samples",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "health_insights",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("insight_type", sa.String(length=50), nullable=True),
        sa.Column("financial_impact", sa.JSON(), nullable=False),
        sa.Column("related_metrics", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_insights_created_at"),
        "health_insights",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_insights_insight_type"),
        "health_insights",
        ["insight_type"],
        unique=False,
    )
    op.create_index(
        "ix_health_insights_user_created",
        "health_insights",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_health_insights_user_dismissed",
        "health_insights",
        ["user_id", "dismissed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_insights_user_id"), "health_insights", ["user_id"], unique=False
    )
    op.create_table(
        "health_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_HEALTH",
                "WHOOP",
                "FITBIT",
                "GARMIN",
                "OURA",
                "GOOGLE_FIT",
                name="healthprovider",
            ),
            nullable=False,
        ),
        sa.Column(
            "metric_type",
            sa.Enum(
                "HEART_RATE",
                "HRV",
                "STEPS",
                "SLEEP_DURATION",
                "SLEEP_QUALITY",
                "CALORIES",
                "WORKOUT",
                "WEIGHT",
                "BLOOD_PRESSURE",
                "OXYGEN_SATURATION",
                name="metrictype",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_metrics_metric_type"),
        "health_metrics",
        ["metric_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_metrics_timestamp"),
        "health_metrics",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_metrics_user_id"), "health_metrics", ["user_id"], unique=False
    )
    op.create_index(
        "ix_health_metrics_user_time",
        "health_metrics",
        ["user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_health_metrics_user_type_time",
        "health_metrics",
        ["user_id", "metric_type", "timestamp"],
        unique=False,
    )
    op.create_table(
        "health_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("diet_style", sa.String(), nullable=True),
        sa.Column("water_intake_range", sa.String(), nullable=True),
        sa.Column("smoking_pattern", sa.String(), nullable=True),
        sa.Column("alcohol_pattern", sa.String(), nullable=True),
        sa.Column("stress_level", sa.String(), nullable=True),
        sa.Column("energy_pattern", sa.String(), nullable=True),
        sa.Column("activity_self_report", sa.String(), nullable=True),
        sa.Column("lifestyle_habits_json", sa.JSON(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_profiles_user_id"), "health_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "health_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("score_date", sa.Date(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sleep_score", sa.Float(), nullable=False),
        sa.Column("movement_score", sa.Float(), nullable=False),
        sa.Column("recovery_score", sa.Float(), nullable=False),
        sa.Column("nutrition_score", sa.Float(), nullable=False),
        sa.Column("lifestyle_score", sa.Float(), nullable=False),
        sa.Column(
            "time_window",
            sa.Enum("LAST_7_DAYS", "LAST_30_DAYS", "LAST_90_DAYS", name="healthwindow"),
            nullable=False,
        ),
        sa.Column("data_sources_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_health_confidence_0_1"
        ),
        sa.CheckConstraint(
            "lifestyle_score >= 0 AND lifestyle_score <= 100",
            name="ck_health_lifestyle_score",
        ),
        sa.CheckConstraint(
            "movement_score >= 0 AND movement_score <= 100",
            name="ck_health_movement_score",
        ),
        sa.CheckConstraint(
            "nutrition_score >= 0 AND nutrition_score <= 100",
            name="ck_health_nutrition_score",
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name="ck_health_overall_score",
        ),
        sa.CheckConstraint(
            "recovery_score >= 0 AND recovery_score <= 100",
            name="ck_health_recovery_score",
        ),
        sa.CheckConstraint(
            "sleep_score >= 0 AND sleep_score <= 100", name="ck_health_sleep_score"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "time_window",
            "score_date",
            name="uq_healthscore_user_window_date",
        ),
    )
    op.create_index(
        op.f("ix_health_scores_score_date"),
        "health_scores",
        ["score_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_scores_timestamp"), "health_scores", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_health_scores_user_id"), "health_scores", ["user_id"], unique=False
    )
    op.create_table(
        "health_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_HEALTH",
                "WHOOP",
                "FITBIT",
                "GARMIN",
                "OURA",
                "GOOGLE_FIT",
                name="healthprovider",
            ),
            nullable=False,
        ),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "sync_frequency",
            sa.Enum("REALTIME", "HOURLY", "DAILY", "WEEKLY", name="syncfrequency"),
            nullable=False,
        ),
        sa.Column("data_categories", sa.JSON(), nullable=False),
        sa.Column(
            "last_modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_health_settings_user_provider"
        ),
    )
    op.create_index(
        op.f("ix_health_settings_user_id"), "health_settings", ["user_id"], unique=False
    )
    op.create_table(
        "investment_portfolios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("institution_name", sa.String(length=100), nullable=False),
        sa.Column("portfolio_name", sa.String(length=255), nullable=True),
        sa.Column("total_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "daily_change_percent", sa.Numeric(precision=7, scale=4), nullable=True
        ),
        sa.Column(
            "total_return_percent", sa.Numeric(precision=7, scale=4), nullable=True
        ),
        sa.Column("asset_allocation_json", sa.JSON(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "institution_name",
            "portfolio_name",
            name="uq_portfolio_user_institution_name",
        ),
    )
    op.create_index(
        op.f("ix_investment_portfolios_last_updated"),
        "investment_portfolios",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investment_portfolios_user_id"),
        "investment_portfolios",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "life_goals_v2",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("target_amount", sa.Float(), nullable=False),
        sa.Column("saved_amount", sa.Float(), nullable=True),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("pillar", sa.String(), nullable=True),
        sa.Column("monthly_contribution_target", sa.Float(), nullable=True),
        sa.Column("impact_vector_json", sa.JSON(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_life_goals_v2_user_id"), "life_goals_v2", ["user_id"], unique=False
    )
    op.create_table(
        "lifestyle_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DINING",
                "CONCERT",
                "SPORTS",
                "TRAVEL",
                "LEISURE",
                name="lifestyleeventtype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("cost_estimated", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "source", "external_id", name="uq_lifestyle_source_external"
        ),
    )
    op.create_index(
        op.f("ix_lifestyle_events_created_at"),
        "lifestyle_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lifestyle_events_start_time"),
        "lifestyle_events",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lifestyle_events_updated_at"),
        "lifestyle_events",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lifestyle_events_user_id"),
        "lifestyle_events",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_lifestyle_user_time",
        "lifestyle_events",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_index(
        "ix_lifestyle_user_type",
        "lifestyle_events",
        ["user_id", "event_type"],
        unique=False,
    )
    op.create_table(
        "mobility_trips",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("pickup_time", sa.DateTime(), nullable=True),
        sa.Column("dropoff_time", sa.DateTime(), nullable=True),
        sa.Column("cost_amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("trip_type", sa.String(), nullable=True),
        sa.Column("origin_lat", sa.Float(), nullable=True),
        sa.Column("origin_lon", sa.Float(), nullable=True),
        sa.Column("destination_lat", sa.Float(), nullable=True),
        sa.Column("destination_lon", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mobility_trips_user_id"), "mobility_trips", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "nutrition_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("calories_in", sa.Integer(), nullable=False),
        sa.Column("protein_grams", sa.Float(), nullable=False),
        sa.Column("carbs_grams", sa.Float(), nullable=False),
        sa.Column("fat_grams", sa.Float(), nullable=False),
        sa.Column("water_liters", sa.Float(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "MYFITNESSPAL",
                "LOSEIT",
                "CRONOMETER",
                "APPLE_HEALTH",
                name="nutritionsource",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_nutrition_user_date"),
    )
    op.create_index(
        op.f("ix_nutrition_logs_date"), "nutrition_logs", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_nutrition_logs_id"), "nutrition_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_nutrition_logs_user_id"), "nutrition_logs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_nutrition_user_date", "nutrition_logs", ["user_id", "date"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_timestamp"),
        "recommendations",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "recurring_bills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("cadence", sa.String(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recurring_bills_user_id"), "recurring_bills", ["user_id"], unique=False
    )
    op.create_table(
        "sleep_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("deep_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("wake_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sleep_sessions_user_id"), "sleep_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "statements",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("total_credits", sa.Float(), nullable=True),
        sa.Column("total_debits", sa.Float(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statements_user_id"), "statements", ["user_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=True),
        sa.Column("current_period_end", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("provider_subscription_id", sa.String(), nullable=True),
        sa.Column("provider_customer_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_provider_subscription_id"),
        "subscriptions",
        ["provider_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="loglevel"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("module", sa.String(length=255), nullable=True),
        sa.Column("function_name", sa.String(length=255), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_logs_id"), "system_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_module"), "system_logs", ["module"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_request_id"), "system_logs", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_timestamp"), "system_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_user_id"), "system_logs", ["user_id"], unique=False
    )
    op.create_table(
        "time_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_events_start_time"), "time_events", ["start_time"], unique=False
    )
    op.create_index(
        op.f("ix_time_events_user_id"), "time_events", ["user_id"], unique=False
    )
    op.create_table(
        "time_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("work_status", sa.String(), nullable=True),
        sa.Column("work_hours_per_week", sa.String(), nullable=True),
        sa.Column("uses_digital_calendar", sa.String(), nullable=True),
        sa.Column("commute_duration", sa.String(), nullable=True),
        sa.Column("time_meals_house_daily", sa.String(), nullable=True),
        sa.Column("time_admin_weekly", sa.String(), nullable=True),
        sa.Column("main_time_drains", sa.JSON(), nullable=True),
        sa.Column("routine_style", sa.String(), nullable=True),
        sa.Column("task_style", sa.String(), nullable=True),
        sa.Column("time_overwhelm_level", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_profiles_user_id"), "time_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "time_scores_v2",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("structure_score", sa.Float(), nullable=True),
        sa.Column("load_score", sa.Float(), nullable=True),
        sa.Column("focus_score", sa.Float(), nullable=True),
        sa.Column("friction_score", sa.Float(), nullable=True),
        sa.Column("stress_score", sa.Float(), nullable=True),
        sa.Column("time_window", sa.String(), nullable=True),
        sa.Column("data_sources_json", sa.JSON(), nullable=True),
        sa.Column("total_scheduled_hours", sa.Float(), nullable=True),
        sa.Column("total_meeting_hours", sa.Float(), nullable=True),
        sa.Column("total_focus_hours", sa.Float(), nullable=True),
        sa.Column("avg_events_per_day", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_scores_v2_timestamp"),
        "time_scores_v2",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_scores_v2_user_id"), "time_scores_v2", ["user_id"], unique=False
    )
    op.create_table(
        "user_health_indexes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("financial_index", sa.Float(), nullable=False),
        sa.Column("time_index", sa.Float(), nullable=False),
        sa.Column("balance_index", sa.Float(), nullable=False),
        sa.Column(
            "time_window",
            sa.Enum(
                "LAST_7_DAYS",
                "LAST_30_DAYS",
                "LAST_90_DAYS",
                "ALL_TIME",
                name="timewindow",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("data_sources", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "time_window", name="uq_user_index_window"),
    )
    op.create_index(
        op.f("ix_user_health_indexes_user_id"),
        "user_health_indexes",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_index_calculated",
        "user_health_indexes",
        ["user_id", "calculated_at"],
        unique=False,
    )
    op.create_table(
        "user_limit_overrides",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("overrides_json", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_limit_overrides_user_id"),
        "user_limit_overrides",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("financial_score", sa.Float(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        sa.Column("time_score", sa.Float(), nullable=False),
        sa.Column("balance_score", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("savings_rate", sa.Float(), nullable=False),
        sa.Column("debt_to_income", sa.Float(), nullable=False),
        sa.Column("emergency_fund_months", sa.Float(), nullable=False),
        sa.Column("investment_diversity", sa.Float(), nullable=False),
        sa.Column("sleep_quality", sa.Float(), nullable=False),
        sa.Column("activity_level", sa.Float(), nullable=False),
        sa.Column("stress_level", sa.Float(), nullable=False),
        sa.Column("nutrition_score", sa.Float(), nullable=False),
        sa.Column("productivity_score", sa.Float(), nullable=False),
        sa.Column("focus_time_hours", sa.Float(), nullable=False),
        sa.Column("meeting_hours", sa.Float(), nullable=False),
        sa.Column("work_life_balance", sa.Float(), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_score >= 0 AND balance_score <= 100",
            name="ck_user_scores_balance_0_100",
        ),
        sa.CheckConstraint("debt_to_income >= 0", name="ck_user_scores_debt_to_income"),
        sa.CheckConstraint(
            "financial_score >= 0 AND financial_score <= 100",
            name="ck_user_scores_financial_0_100",
        ),
        sa.CheckConstraint(
            "health_score >= 0 AND health_score <= 100",
            name="ck_user_scores_health_0_100",
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name="ck_user_scores_overall_0_100",
        ),
        sa.CheckConstraint(
            "savings_rate >= 0 AND savings_rate <= 2",
            name="ck_user_scores_savings_rate",
        ),
        sa.CheckConstraint(
            "time_score >= 0 AND time_score <= 100", name="ck_user_scores_time_0_100"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_scores_user_id"),
    )
    op.create_index(
        op.f("ix_user_scores_created_at"), "user_scores", ["created_at"], unique=False
    )
    op.create_index(
        "ix_user_scores_updated", "user_scores", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_scores_updated_at"), "user_scores", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_scores_user_id"), "user_scores", ["user_id"], unique=False
    )
    op.create_table(
        "viv_indexes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("financial_score", sa.Float(), nullable=True),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("time_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("snapshot_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_viv_index_user_timestamp",
        "viv_indexes",
        ["user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_viv_indexes_timestamp"), "viv_indexes", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_viv_indexes_user_id"), "viv_indexes", ["user_id"], unique=False
    )
    op.create_table(
        "viv_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_intent", sa.String(), nullable=True),
        sa.Column("context_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("decision_logic", sa.Text(), nullable=True),
        sa.Column("ai_response", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_viv_logs_timestamp"), "viv_logs", ["timestamp"], unique=False
    )
    op.create_index(op.f("ix_viv_logs_user_id"), "viv_logs", ["user_id"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("average_heart_rate", sa.Integer(), nullable=True),
        sa.Column("perceived_exertion", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_table(
        "transactions_v2",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=True),
        sa.Column("statement_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=True),
        sa.Column("transaction_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("merchant_name", sa.String(), nullable=True),
        sa.Column("merchant_category_code", sa.String(), nullable=True),
        sa.Column("category_primary", sa.String(), nullable=True),
        sa.Column("category_detailed", sa.String(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("deduplication_key", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["financial_accounts_v2.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transactions_user_date",
        "transactions_v2",
        ["user_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_v2_account_id"),
        "transactions_v2",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_v2_deduplication_key"),
        "transactions_v2",
        ["deduplication_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transactions_v2_statement_id"),
        "transactions_v2",
        ["statement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_v2_transaction_date"),
        "transactions_v2",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_v2_user_id"), "transactions_v2", ["user_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("service_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("amount_estimated", sa.Float(), nullable=True),
        sa.Column("amount_final", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("external_order_id", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions_v2.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_external_order_id"),
        "orders",
        ["external_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_idempotency_key"), "orders", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_idempotency_key"), table_name="orders")
    op.drop_index(op.f("ix_orders_external_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_transactions_v2_user_id"), table_name="transactions_v2")
    op.drop_index(
        op.f("ix_transactions_v2_transaction_date"), table_name="transactions_v2"
    )
    op.drop_index(op.f("ix_transactions_v2_statement_id"), table_name="transactions_v2")
    op.drop_index(
        op.f("ix_transactions_v2_deduplication_key"), table_name="transactions_v2"
    )
    op.drop_index(op.f("ix_transactions_v2_account_id"), table_name="transactions_v2")
    op.drop_index("idx_transactions_user_date", table_name="transactions_v2")
    op.drop_table("transactions_v2")
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_viv_logs_user_id"), table_name="viv_logs")
    op.drop_index(op.f("ix_viv_logs_timestamp"), table_name="viv_logs")
    op.drop_table("viv_logs")
    op.drop_index(op.f("ix_viv_indexes_user_id"), table_name="viv_indexes")
    op.drop_index(op.f("ix_viv_indexes_timestamp"), table_name="viv_indexes")
    op.drop_index("idx_viv_index_user_timestamp", table_name="viv_indexes")
    op.drop_table("viv_indexes")
    op.drop_index(op.f("ix_user_scores_user_id"), table_name="user_scores")
    op.drop_index(op.f("ix_user_scores_updated_at"), table_name="user_scores")
    op.drop_index("ix_user_scores_updated", table_name="user_scores")
    op.drop_index(op.f("ix_user_scores_created_at"), table_name="user_scores")
    op.drop_table("user_scores")
    op.drop_index(
        op.f("ix_user_limit_overrides_user_id"), table_name="user_limit_overrides"
    )
    op.drop_table("user_limit_overrides")
    op.drop_index("ix_user_index_calculated", table_name="user_health_indexes")
    op.drop_index(
        op.f("ix_user_health_indexes_user_id"), table_name="user_health_indexes"
    )
    op.drop_table("user_health_indexes")
    op.drop_index(op.f("ix_time_scores_v2_user_id"), table_name="time_scores_v2")
    op.drop_index(op.f("ix_time_scores_v2_timestamp"), table_name="time_scores_v2")
    op.drop_table("time_scores_v2")
    op.drop_index(op.f("ix_time_profiles_user_id"), table_name="time_profiles")
    op.drop_table("time_profiles")
    op.drop_index(op.f("ix_time_events_user_id"), table_name="time_events")
    op.drop_index(op.f("ix_time_events_start_time"), table_name="time_events")
    op.drop_table("time_events")
    op.drop_index(op.f("ix_system_logs_user_id"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_timestamp"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_request_id"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_module"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_id"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(
        op.f("ix_subscriptions_provider_subscription_id"), table_name="subscriptions"
    )
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_statements_user_id"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(op.f("ix_sleep_sessions_user_id"), table_name="sleep_sessions")
    op.drop_table("sleep_sessions")
    op.drop_index(op.f("ix_recurring_bills_user_id"), table_name="recurring_bills")
    op.drop_table("recurring_bills")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_timestamp"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("ix_nutrition_user_date", table_name="nutrition_logs")
    op.drop_index(op.f("ix_nutrition_logs_user_id"), table_name="nutrition_logs")
    op.drop_index(op.f("ix_nutrition_logs_id"), table_name="nutrition_logs")
    op.drop_index(op.f("ix_nutrition_logs_date"), table_name="nutrition_logs")
    op.drop_table("nutrition_logs")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_mobility_trips_user_id"), table_name="mobility_trips")
    op.drop_table("mobility_trips")
    op.drop_index("ix_lifestyle_user_type", table_name="lifestyle_events")
    op.drop_index("ix_lifestyle_user_time", table_name="lifestyle_events")
    op.drop_index(op.f("ix_lifestyle_events_user_id"), table_name="lifestyle_events")
    op.drop_index(op.f("ix_lifestyle_events_updated_at"), table_name="lifestyle_events")
    op.drop_index(op.f("ix_lifestyle_events_start_time"), table_name="lifestyle_events")
    op.drop_index(op.f("ix_lifestyle_events_created_at"), table_name="lifestyle_events")
    op.drop_table("lifestyle_events")
    op.drop_index(op.f("ix_life_goals_v2_user_id"), table_name="life_goals_v2")
    op.drop_table("life_goals_v2")
    op.drop_index(
        op.f("ix_investment_portfolios_user_id"), table_name="investment_portfolios"
    )
    op.drop_index(
        op.f("ix_investment_portfolios_last_updated"),
        table_name="investment_portfolios",
    )
    op.drop_table("investment_portfolios")
    op.drop_index(op.f("ix_health_settings_user_id"), table_name="health_settings")
    op.drop_table("health_settings")
    op.drop_index(op.f("ix_health_scores_user_id"), table_name="health_scores")
    op.drop_index(op.f("ix_health_scores_timestamp"), table_name="health_scores")
    op.drop_index(op.f("ix_health_scores_score_date"), table_name="health_scores")
    op.drop_table("health_scores")
    op.drop_index(op.f("ix_health_profiles_user_id"), table_name="health_profiles")
    op.drop_table("health_profiles")
    op.drop_index("ix_health_metrics_user_type_time", table_name="health_metrics")
    op.drop_index("ix_health_metrics_user_time", table_name="health_metrics")
    op.drop_index(op.f("ix_health_metrics_user_id"), table_name="health_metrics")
    op.drop_index(op.f("ix_health_metrics_timestamp"), table_name="health_metrics")
    op.drop_index(op.f("ix_health_metrics_metric_type"), table_name="health_metrics")
    op.drop_table("health_metrics")
    op.drop_index(op.f("ix_health_insights_user_id"), table_name="health_insights")
    op.drop_index("ix_health_insights_user_dismissed", table_name="health_insights")
    op.drop_index("ix_health_insights_user_created", table_name="health_insights")
    op.drop_index(op.f("ix_health_insights_insight_type"), table_name="health_insights")
    op.drop_index(op.f("ix_health_insights_created_at"), table_name="health_insights")
    op.drop_table("health_insights")
    op.drop_index(
        op.f("ix_health_data_samples_user_id"), table_name="health_data_samples"
    )
    op.drop_index(op.f("ix_health_data_samples_date"), table_name="health_data_samples")
    op.drop_table("health_data_samples")
    op.drop_index(
        op.f("ix_health_daily_summaries_user_id"), table_name="health_daily_summaries"
    )
    op.drop_index(
        op.f("ix_health_daily_summaries_date"), table_name="health_daily_summaries"
    )
    op.drop_index("idx_health_summary_user_date", table_name="health_daily_summaries")
    op.drop_table("health_daily_summaries")
    op.drop_index(
        op.f("ix_health_connections_user_id"), table_name="health_connections"
    )
    op.drop_index(
        op.f("ix_health_connections_provider"), table_name="health_connections"
    )
    op.drop_index("ix_health_conn_user_status", table_name="health_connections")
    op.drop_table("health_connections")
    op.drop_index(op.f("ix_financial_scores_user_id"), table_name="financial_scores")
    op.drop_index(op.f("ix_financial_scores_timestamp"), table_name="financial_scores")
    op.drop_table("financial_scores")
    op.drop_index(
        op.f("ix_financial_accounts_v2_user_id"), table_name="financial_accounts_v2"
    )
    op.drop_table("financial_accounts_v2")
    op.drop_index(op.f("ix_feature_interests_user_id"), table_name="feature_interests")
    op.drop_table("feature_interests")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_connections_user_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_calendar_events_user_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_start_time"), table_name="calendar_events")
    op.drop_index("idx_calendar_events_user_start", table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_bug_reports_user_id"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_status"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_request_id"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_id"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_error_type"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_endpoint"), table_name="bug_reports")
    op.drop_table("bug_reports")
    op.drop_index("ix_bgjob_status_updated", table_name="background_jobs")
    op.drop_index("ix_bgjob_expires_at", table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_user_id"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_updated_at"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_job_type"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_dedupe_key"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_created_at"), table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index(op.f("ix_activity_feed_user_id"), table_name="activity_feed")
    op.drop_index(op.f("ix_activity_feed_event_type"), table_name="activity_feed")
    op.drop_index(op.f("ix_activity_feed_created_at"), table_name="activity_feed")
    op.drop_index(op.f("ix_activity_feed_correlation_id"), table_name="activity_feed")
    op.drop_table("activity_feed")
    op.drop_index(op.f("ix_users_v2_password_reset_token"), table_name="users_v2")
    op.drop_index(op.f("ix_users_v2_email"), table_name="users_v2")
    op.drop_index(op.f("ix_users_v2_auth0_id"), table_name="users_v2")
    op.drop_table("users_v2")
    op.drop_index(op.f("ix_tier_configs_plan_id"), table_name="tier_configs")
    op.drop_table("tier_configs")
    op.drop_table("onboarding_sessions")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
