name: Deploy to Staging and Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging and Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Set up gcloud CLI
      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: newprojectlfsd
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-cluster-lfsd --region us-central1 --project newprojectlfsd

      # Deploy to Staging
      - name: Deploy to Staging
        run: |
          kubectl apply -f k8s/staging-deployment.yaml

      # Deploy to Production
      - name: Deploy to Production
        if: success()
        run: |
          kubectl apply -f k8s/production-deployment.yaml
