name: Docker Build and Push

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Image
        run: |
          docker build -t hamoum/lfsd:latest -f ./docker/Dockerfile .
          docker push hamoum/lfsd:latest
